### ISSUE TITLE
Release version 1.1.0

### ISSUE THREAD

**Issue by Xuanwo** [beyondstorage/go-endpoint#12]
We need to cut off a release so that we can use in https://github.com/beyondstorage/go-service-hdfs/pull/15

**Comment by Xuanwo** [comment]
@abyss-w Could you take time to bump the version here? (It's the normal release process for all our projects.)

**Comment by abyss-w** [comment]
> @abyss-w Could you take time to bump the version here? (It's the normal release process for all our projects.)

Okay, got it.

**Comment by abyss-w** [comment]
ping @Xuanwo, I don't have permission to add a tag and release version, could you please add a tag and release version?
