### ISSUE TITLE
Add FTP endpoint pair

### ISSUE THREAD

**Issue by npofsi** [beyondstorage/go-endpoint#14]
go-service-ftp now use `tcp://` protocol to access to file server which is less precise.
I proposal to add an endpoint pair `ftp://` like `tcp://`, which uses same way to obtain host and port

**Comment by Xuanwo** [comment]
For now, I don't think we need an `ftp` protocol. FTP is a protocol based on TCP, so we will use `tcp` as an endpoint to connect an FTP server. The real problem we meet here is ftp protocol only supports TCP, and itself is a widely used protocol.

Maybe we need to support default protocol for endpoint:

Turn `ftp://?endpoint=tcp:127.0.0.1:1080` into `ftp://?endpoint=127.0.0.1:1080`.
